// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQIC3Diy11EHtRVLK7fwpKbtAWlXDtF8',
    appId: '1:297252932401:web:36d8ad5b6ce5ff7ffebe10',
    messagingSenderId: '297252932401',
    projectId: 'ihdaa-dfaae',
    authDomain: 'ihdaa-dfaae.firebaseapp.com',
    storageBucket: 'ihdaa-dfaae.appspot.com',
    measurementId: 'G-TFWMWJPJJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYlStt76RMRTbxzqPitj-0o2VLWZHmeOA',
    appId: '1:297252932401:android:18ff1522b256132dfebe10',
    messagingSenderId: '297252932401',
    projectId: 'ihdaa-dfaae',
    storageBucket: 'ihdaa-dfaae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10jxbokBsUL16IlV3JvOmcgMF2Py5kHU',
    appId: '1:297252932401:ios:38ed347b249144b9febe10',
    messagingSenderId: '297252932401',
    projectId: 'ihdaa-dfaae',
    storageBucket: 'ihdaa-dfaae.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA10jxbokBsUL16IlV3JvOmcgMF2Py5kHU',
    appId: '1:297252932401:ios:38ed347b249144b9febe10',
    messagingSenderId: '297252932401',
    projectId: 'ihdaa-dfaae',
    storageBucket: 'ihdaa-dfaae.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyQIC3Diy11EHtRVLK7fwpKbtAWlXDtF8',
    appId: '1:297252932401:web:f742dd49da54dfb1febe10',
    messagingSenderId: '297252932401',
    projectId: 'ihdaa-dfaae',
    authDomain: 'ihdaa-dfaae.firebaseapp.com',
    storageBucket: 'ihdaa-dfaae.appspot.com',
    measurementId: 'G-DHRL07VVKB',
  );
}
